#!/usr/bin/env python3
import urllib.request, urllib.parse, json, sys, os

user = 'jib1337'

page = 1
while True:
    with urllib.request.urlopen(f'https://api.github.com/users/{user}/starred?per_page=100&page={page}') as response:
        try:
            if page == 1:
                stardata = json.load(response)
            else:
                nextpage = json.load(response)
                
                if len(nextpage) > 0:
                    stardata.append(nextpage)
                else:
                    break

            if 'documentation_url' in stardata:
                print('Error: user doesnt exist')
                quit()

        except ValueError:
            print('Error: failure to retrieve valid star data')
            quit()

    page+= 1

if len(sys.argv) > 1:
    if sys.argv[1].isdigit() and int(sys.argv[1]) > 0 and int(sys.argv[1]) <= len(stardata):
        os.system(f"git clone https://github.com/{stardata[int(sys.argv[1])-1]['full_name']}.git")
        quit()
    else:
        print('Invalid argument.\n')

longest = len(max([repo['full_name'] for repo in stardata], key=len))

for i, repo in enumerate(stardata):
    print(f"{i+1}.\t{repo['full_name']:{longest+1}}", end='')
    if repo['description'] is not None:
        print(repo['description'][:80])
    else:
        print()
